config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/service'
  get 'home/contact'
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def service
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="about_container">
   
            <div class="title_container">
                <h2 class="title-section">The number #1  Company</h2>
            <div class="divider"></div>
            <p class="param-section">
                Est velit elit nostrud eiusmod sit. Exercitation Lorem eiusmod do commodo reprehenderit cupidatat laborum magna in occaecat consectetur labore veniam velit. Duis in consectetur occaecat dolore labore tempor velit anim dolor magna pariatur. Anim ad dolore fugiat nulla esse nisi sint sint amet eu sit aliquip ullamco. Esse ad do magna qui.
            </p>
            <p class="param-section">At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
            <p class="param-section">Sit esse tempor duis non ex consectetur sit tempor laboris mollit. Id id cillum tempor fugiat. Deserunt consectetur minim velit ea reprehenderit eu cupidatat. Eu deserunt veniam minim culpa aliqua amet aliqua ex. Veniam qui laboris proident pariatur non labore mollit anim. Consequat eiusmod ut officia culpa deserunt non culpa dolor ex amet in ullamco duis eiusmod. Cupidatat cillum exercitation aliquip labore.</p>
        </div>
        
        <div>
            <div>
                <%= image_tag ("about_frame.png") %>
            </div>
        </div>

    
</div>

app/views/home/contact.html.erb
<div class="background">
  <div class="blur">
    <div class='details-section'>
      
        <div  class='params-section'>
            <p class='sub-params'>203 Fake St. Mountain View, San Francisco, California, USA</p>
        </div>
        <div  class='params-section'>
            <p class='sub-params'>+00 1122 3344 5566 </p>
        </div>
        <div  class='params-section'>
            <p class='sub-params'>abc@temporary.com </p>
        </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home_container">
  <div class="blur">
    <div class="main_heading-section">
       
            <h1 class="h1-heading">Welcome To Company Template</h1>
 
    </div>
  </div>
</div>

app/views/home/service.html.erb
<div class="page-section bg-light">
    <div class="container">
      <div class="heading_container">
        <div class="subhead">Our services</div>
        <h2 class="title-section">How Our Team Can Help</h2>
        <div class="divider"></div>
      </div>

        <div class="row">
            <div class="service-section">
                    <div class="service_image_container">
                        <%= image_tag("bussiness")%>
                    </div>
                    <div class='content-section'>
                        <h5 class='h5-title'>OnSite </h5>
                        <p class='p-section'>We analyse your website's structure, internal architecture & other key</p>
                        <p class='p-section'>Sit veniam do aliqua velit id et ea ex amet veniam voluptate. Velit consequat aliqua nisi eu occaecat voluptate nulla minim. Officia ipsum et do cillum ea aute pariatur aliqua aliqua laboris quis enim cupidatat. Deserunt enim adipisicing nostrud mollit fugiat id magna minim dolore dolore occaecat nulla nostrud sit.</p>
                    </div>
            </div>
            <div class="service-section" id="reverse-section">
                    <div class="service_image_container">
                        <%= image_tag("bussiness")%>
                    </div>
                  <div class='content-section'>
                        <h5 class='h5-title'>OnSite </h5>
                        <p class='p-section'>We analyse your website's structure, internal architecture & other key</p>
                        <p class='p-section'>Sit veniam do aliqua velit id et ea ex amet veniam voluptate. Velit consequat aliqua nisi eu occaecat voluptate nulla minim. Officia ipsum et do cillum ea aute pariatur aliqua aliqua laboris quis enim cupidatat. Deserunt enim adipisicing nostrud mollit fugiat id magna minim dolore dolore occaecat nulla nostrud sit.</p>
                    </div>
            </div>
            <div class="service-section">
                    <div class="service_image_container">
                        <%= image_tag("bussiness")%>
                    </div>
                    <div class='content-section'>
                        <h5 class='h5-title'>OnSite </h5>
                        <p class='p-section'>We analyse your website's structure, internal architecture & other key</p>
                        <p class='p-section'>Sit veniam do aliqua velit id et ea ex amet veniam voluptate. Velit consequat aliqua nisi eu occaecat voluptate nulla minim. Officia ipsum et do cillum ea aute pariatur aliqua aliqua laboris quis enim cupidatat. Deserunt enim adipisicing nostrud mollit fugiat id magna minim dolore dolore occaecat nulla nostrud sit.</p>
                    </div>
            </div>
            <div class="service-section" id="reverse-section">
                    <div class="service_image_container" >
                        <%= image_tag("bussiness")%>
                    </div>
                    <div class='content-section'>
                        <h5 class='h5-title'>OnSite </h5>
                        <p class='p-section'>We analyse your website's structure, internal architecture & other key</p>
                        <p class='p-section'>Sit veniam do aliqua velit id et ea ex amet veniam voluptate. Velit consequat aliqua nisi eu occaecat voluptate nulla minim. Officia ipsum et do cillum ea aute pariatur aliqua aliqua laboris quis enim cupidatat. Deserunt enim adipisicing nostrud mollit fugiat id magna minim dolore dolore occaecat nulla nostrud sit.</p>
                    </div>
            </div>
           
        </div>

    </div> <!-- .container -->
</div> <!-- .page-section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyWebApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="container">
      <nav> 
        <ul>
        <li> <%= link_to "Home", root_path %> </li>
        <li> <%= link_to "Services", home_service_path %> </li>
          <li> <%= link_to "About Us", home_about_path %> </li>
          <li> <%= link_to "Contact Us", home_contact_path %> </li>
        </ul>
      </nav>
    </div>
  </header>

  <%= yield %>
  </body>
</html>